### ISSUE TITLE
Question: Correct usage of a PrismaticJoint (Line Constraint)

### ISSUE THREAD

**Issue by DubWa91** [dyn4j/dyn4j#107]
Hi William,
due to the fact, that the forum is no longer active I have to use an issue to ask a question about the correct usage of the `PrismaticJoint` as a Line Constraint.

I have serveral `SimulationBody` objects arranged on a specific Y level (the bottom side). These objects are also connected via `DistanceJoint` to maintain a specific distance. After the initialization the bodies will move closer to each other based on the resulting spring-forces. The bodies on that Y level should not rotate (move along the "line").

Please see my picture for the use-case.

![grafik](https://user-images.githubusercontent.com/34217758/76067121-24c3df80-5f8f-11ea-8c3d-236f7d7d34b5.png)

I solved it with the following code:
``
	
	protected void initializeWorld()
	{
		// no gravity on a top-down view of a billiards game
		this.world.setGravity(World.ZERO_GRAVITY);

		// Setup Layout-Border
		this.setupLayout();

		double xLevelStart = -1.0;
		double yLevelStart = 0.0;
	
		
		SimulationBody simulationBodyA = this.createSimulationBody(0.1, 0.2, "1");
		simulationBodyA.translate(new Vector2(xLevelStart, yLevelStart + 0.1));	// Half the height added
		simulationBodyA.setMass(MassType.FIXED_ANGULAR_VELOCITY);
		this.world.addBody(simulationBodyA);
		
		// Create SimulationBodyB
		SimulationBody simulationBodyB = this.createSimulationBody(0.2, 0.4, "2");
		simulationBodyB.translate(new Vector2(xLevelStart * -1, yLevelStart + 0.2)); // Half the height added
		simulationBodyB.setMass(MassType.FIXED_ANGULAR_VELOCITY);
		this.world.addBody(simulationBodyB);

		// Create a DistanceJoint
		DistanceJoint distanceJoint = new DistanceJoint(simulationBodyA, simulationBodyB, new Vector2(simulationBodyA.getWorldCenter().x, yLevelStart), new Vector2(simulationBodyB.getWorldCenter().x, yLevelStart));
		distanceJoint.setCollisionAllowed(true);
		distanceJoint.setDistance(0.5);
		distanceJoint.setDampingRatio(0.5);
		distanceJoint.setFrequency(0.9);
		this.world.addJoint(distanceJoint);
	}
``

The result you can see on that picture.
![grafik](https://user-images.githubusercontent.com/34217758/76067777-3a85d480-5f90-11ea-90b5-62d2b81c5d23.png)

But this is more or less a work-around in my opinion.

How is it possible to setup a constraint (I guess I have to use the `PrismaticJoint`) so that the bodies are only allowed to move along a defined line?

See for example the picture below.
![grafik](https://user-images.githubusercontent.com/34217758/76067900-74ef7180-5f90-11ea-8631-3bf03efea6fc.png)

Are there some conditions I have to meet to make the same behaviour possible with the `PrismaticJoint`? Because I get some strange behaviours when I set the WorldAnchorPoint vector and the Axis vector.

I hope you can understand my question. Otherwise I try to rephrase it.

Thanks in advance,

Carsten

**Comment by wnbittle** [comment]
I think I understand the question and you are in the correct place.

The PrismaticJoint does indeed restrict rotation and linear movement along the axis of the two joined bodies.  Don’t forget that you can have multiple joints joining the same pair of bodies as well.

The special mass types are meant to be used, but it is possible that they have unintended consequences.

If you can give more details about the problem you are having with creating the PrismaticJoint, we can help.

**Comment by DubWa91** [comment]
Hi William,

thank you for your reply.

I had a wrong assumption about how to use the `PrismaticJoint`.

For my specific topic I introduced an additional `SimulationBody` with `MassType.INFINITE` as a reference.

With that one I can create my "Y-level" (line) constraint.

![grafik](https://user-images.githubusercontent.com/34217758/76210210-f1d65180-6203-11ea-8706-3e3a086e0de8.png)

In the picture above the 3 lower bodies should be on the same line (exactly what they are doing).
The upper 2 bodies should be side-by-side regardless their rotation (exactly what they are doing).

Everything is now clear for me.

Thank you for your tip with the multiple joints :)

Regards,

Carsten
