### ISSUE TITLE
Set custom mass, indifferent from body size

### ISSUE THREAD

**Issue by soylomass** [dyn4j/dyn4j#108]
In Box2D I set all my dynamic bodies to have a density of 0. This way, every body, no matter how big it is, seems to weight the same in collisions, and have the same speed when applied the same force.
Is this possible in Dyn4j?

**Comment by wnbittle** [comment]
It is possible to set the density/mass directly, but I’m not sure 0 would give you what you are looking for.

If density is supplied, we take density*area to get the mass, which in this case would be 0.

Using a 0 mass (and by extension 0 density) tells dyn4j to interpret this as an infinite mass body - I’m guessing not what you want?

Are u sure you used 0 box2d?  I’d have to go back and look what it’s doing to see what the differences are between our behavior in this case.

That said you should be able to set the mass of the body directly by creating an instance of mass and supplying the mass, intertia, and center of mass.  In that way you could set all you bodies, regardless of shape to the same mass.

On the flip side, you can specify the density when adding a shape to a body to have a similar effect, but I’m this case the total mass would be dependent on the shape’s area as mentioned earlier.

**Comment by soylomass** [comment]
Yes, in Box2D I set the density to 0,
I emulated a similar result by setting a new Mass after adding fixtures in Dyn4j like you said and achieved the result I needed.
