### ISSUE TITLE
Question: "Static" collision detection

### ISSUE THREAD

**Issue by DubWa91** [dyn4j/dyn4j#109]
Hi William,

How is it possible to use the collision detection in a static way?

To explain my goal I made a drawing.

![grafik](https://user-images.githubusercontent.com/34217758/76874108-fab3cc80-686e-11ea-8b28-b30195c4ab63.png)

Basically I use your library to define the positions of the green rectangles (SimulationBody). -> Equilibrium state reached (= all SimulationBody objects are asleep)

In the next step I rasterize the available space (cells).

Then I want to identify which cell is **totally** empty.

Therefore I created a new SimulationBody with the dimensions of a cell (fixture set as sensor).

Then I "translate" the SimulationBody from cell to cell and check if there is a collision.

Therefore I use the following code I found in your old forum.

```
/**
	 * Use the collision detection pipeline. <br>
	 * Broadphase -> Narrowphase -> Manifold generation
	 */
	private void useCollisionDetectionPipeline()
	{
		System.out.println("Manual usage of collsion pipeline started");
		
	    // Create the detection chain
	    BroadphaseDetector<Body, BodyFixture> bp = new DynamicAABBTree<Body, BodyFixture>();
	    NarrowphaseDetector np = new Gjk();
	    NarrowphasePostProcessor npp = new LinkPostProcessor();  // Only required if you use the Link shape
	    ManifoldSolver ms = new ClippingManifoldSolver();
	     
	    // Setup "world" -> Add bodies to the broadphase
	    for (int i = 1; i < this.world.getBodyCount(); i++)	// i = 0 is the layout frame
		{
			bp.add(this.world.getBodies().get(i));
		}
	     
		// When ready to detect
		List<BroadphasePair<Body, BodyFixture>> pairs = bp.detect();
		for (BroadphasePair<Body, BodyFixture> pair : pairs)
		{
			Body body1 = pair.getCollidable1();
			Body body2 = pair.getCollidable2();
			
			BodyFixture fixture1 = pair.getFixture1();
			BodyFixture fixture2 = pair.getFixture2();
			
			Transform transform1 = body1.getTransform();
			Transform transform2 = body2.getTransform();
			
			Convex convex2 = fixture2.getShape();
			Convex convex1 = fixture1.getShape();
			
			Penetration p = new Penetration();
			
			if (np.detect(convex1, transform1, convex2, transform2, p))
			{
				npp.process(convex1, transform1, convex2, transform2, p);
				Manifold m = new Manifold();
				if (ms.getManifold(p, convex1, transform1, convex2, transform2, m))
				{
					// you have a collision and a manifold to work with
					System.out.println("Collision between " + body1.getUserData() + " and " + body2.getUserData());
				}
			}
		}
	}
```

This works more or less quite well but I was wondering if there is a simpler way to get the same result.

As in my last question I hope you understand my question :D

Otherwise I will provide more information.

Best regard,

Carsten

**Comment by wnbittle** [comment]
Sorry for the delay in responding.  What you've outlined would work, but it won't scale very well.  It's probably the easiest way though.  The best way would be to create a custom broadphase detector that's grid-based.

**Comment by DubWa91** [comment]
Thank you for your reply.

I will have a look at your suggestion :)
