### ISSUE TITLE
Distributed Dyn4J

### ISSUE THREAD

**Issue by assofohdz** [dyn4j/dyn4j#111]
Hi

Was wondering if there was any thoughts as to adding a sort of physics distribution management into Dyn4J. Specifically, im thinking of dividing the world into zones, and keeping track of which zones are active and which are inactive, and only doing simulation for those that are active or about to become active (if something spawned in that zone, if a neighbour zone was active etc.)

**Comment by wnbittle** [comment]
The library has a lot of the machinery to achieve this.  The basic premise would be to create individual Worlds, each with their own defined Bounds to represent the zones.  When a Body is outside the bounds of any one zone, it is moved to the neighboring zone.  If a zone has no bodies in it, it doesn't need to be simulated.

The hard part is the transition from zone to zone.  A couple of cases come to mind:
- A body is partially in both zones.  You can't simulate the body in both worlds so you have to choose which world will simulate it.  The choice you make will obviously determine what objects it interacts with.  One option would be to setup a dead zone between the zones where once the body is in the dead zone it transitions into the neighbor zone.
- A body is outside the zone, but is connected via a joint to another body that's still inside the zone.  For the simulation to work properly, the two bodies and the joint need to be all part of the same World.  This is a much harder problem.

An alternative to this would be to employ some form of stream-able World where the application adds/removes bodies/joints in and out of the world as the player moves.  This has it's own challenges, but has the benefit of solving some of the discrete zone problems described above.

I see this type of structure as a layer on top of dyn4j similar to path finding and rendering.

**Comment by assofohdz** [comment]
Allright. Thank you.
