### ISSUE TITLE
Exception occured after minor modifications in the code

### ISSUE THREAD

**Issue by moleprogrammer** [dyn4j/dyn4j#115]
As I made minor changes in my project, I now have some runs, that throw a `java.util.ConcurrentModificationException`. 
My changes were basically:

- setting a fixture as sensor and 

- picking values from fixtures AABB

But as I mentioned before, I only get this exception in some runs and I use the modified code in all the runs.

```
Exception in thread "Thread-3" java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:739)
	at dyn4j.collision.broadphase.DynamicAABBTree.detect(DynamicAABBTree.java:255)
	at dyn4j.dynamics.World.detect(World.java:732)
	at dyn4j.dynamics.World.step(World.java:663)
	at dyn4j.dynamics.World.update(World.java:395)
	at dyn4j.dynamics.World.update(World.java:290)
	at simulationframework.SimulationFrame.update(SimulationFrame.java:494)
	at simulationframework.SimulationFrame.gameLoop(SimulationFrame.java:266)
	at simulationframework.SimulationFrame.access$0(SimulationFrame.java:236)
	at simulationframework.SimulationFrame$2.run(SimulationFrame.java:208)
```
I have no idea which of my changes caused the appearence of the exception.
I would appreciate to get a idea what is going wrong here.
Thank you very much in advance for other ideas or some hints. :)

**Comment by wnbittle** [comment]
A `ConcurrentModificationException` should only occur in the `DynamicAABBTree` if you are modifying the broadphase while the detect method is executing.  That would include adding new bodies, removing bodies, adding new fixtures to bodies, or removing fixtures from bodies.

It's unlikely you are calling the `DynamicAABBTree` methods directly to cause this problem, but the following methods could if called from the wrong context: `Body.removeFixture`, `Body.addFixture`, `Body.removeAllFixtures`, `Body.getFixtureIterator().remove`, `World.addBody`, `World.removeBody`, `World.getBodyIterator().remove`, `World.removeAllBodies`, and `World.removeAllBodiesAndJoints`.  

These methods should not be called from within the `Listener` methods and all from the same UI/gameloop thread.  The World can be built outside of the main thread, but once the render loop is running - all modifications must happen from within that thread.

Can you post any of the code that's generating this error?

**Comment by moleprogrammer** [comment]
Thank you for that hint. It seems that it was a incorrect use of the addFixture-method. I have modified the code and the exception did not occure since then.

**Comment by moleprogrammer** [comment]
The exception is unfortunately not yet definitively excluded. If the exception occurs in the debug-run, it is always between two nodes of a simulation body that was formed from a link convex.
The body is created using hte following code:

        	List<Link> pointLinks = Geometry.createLinks(pointList, false);
                SimulationBody body = new SimulationBody();
		for (Link link : pointLinks)
		{
			body.addFixture(link);
		}
		body.setMass(MassType.INFINITE);
		body.setColor(Color.BLACK);
		body.setUserData(new DataContainer("test"));
		world.addBody(body);

Did I make a mistake in creating this body?
Thank you very much in advance for other ideas or some hints. :)

**Comment by wnbittle** [comment]
@moleprogrammer Did you find your problem?  All signs point to either:

1. Modifying a list while iterating over it
1. Or running multiple threads and modifying the world (or anything related to it) on multiple threads.
