### ISSUE TITLE
How to implement semi transparent Objects 

### ISSUE THREAD

**Issue by ia97lies** [dyn4j/dyn4j#116]
What I mean is I would like have platforms on which my character can walk but if he jumps from a lover place he does not to be able to jump through it and finally stand on it. Ideas? Pointers?

**Comment by assofohdz** [comment]
Do a check in the broadphase for the direction and return false if the character is jumping upwards (disables any further check on this collision). If he's falling and he collides it should return true, making him collide/stand on the platform

**Comment by wnbittle** [comment]
@ia97lies Did @assofohdz idea work for you?

**Comment by ia97lies** [comment]
I guess this would work that way, I didn't yet try it and I'm not sure if I need it in my game anymore. But thanks a lot @assofohdz
