### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [dyn4j/dyn4j#117]
I converted your Dyn4j engine from Java to Kotlin and want to use it for my commercial projects targeting desktop, android, iOS and browser. Am I allowed to do that? Can I share converted version with people on GitHub?

**Comment by yuripourre** [comment]
https://github.com/dyn4j/dyn4j/blob/master/LICENSE.md

**Comment by dmitrykolesnikovich** [comment]
Does that literally mean I should cooy paste license file and everything is allowed?

**Comment by wnbittle** [comment]
The license allows use in commercial projects and derivative works (like a port) under closed or open source licenses.  The only stipulation is the retention of the copyright notice.

https://opensource.stackexchange.com/questions/2832/derived-work-of-bsd-licensed-software-how-do-i-indicate-this

The link above explains how you could modify the copyright notice to include the author of a derivative work if you kept the same license.

The BSD license is vey permissive though, so you could release it under a copyleft or not at all (propriety) or really any license, provided you include the original.

For a binary redistribution, you’d only need to include the license file somewhere in the distribution.  For a port, you’d likely need to include it on every source file or at least a link/reference to the license on every source file that was a derivative.  That isn’t as clear, but that would be my recommendation.
