### ISSUE TITLE
Question: Maintain specific distance between SimulationBody objects

### ISSUE THREAD

**Issue by DubWa91** [dyn4j/dyn4j#119]
Hi William,

I have again a question.

**Scenario:** 

Different SimulationBody objects, which should keep a defined distance between each other. It is possible, that there are different distances between each pair defined.

**Goal:** 

Some SimulationBody move, some don't, but in the end the defined distance between them should be kept and the collssion methods should be active.

**Identified problem:**

Definition of Joints are not suitable based on the different shapes of SimulationBody objects and the problem with the correct placement of anchor points. For example when a specific distance between a Circle and a Rectangle should be kept it is not suitable to define the anchor points in the center of each SimulationBody. (difference in distance based on dimensions of reactangle).

**Current approach:**

1. Define for each specific distance pair additional fixtures (sensor = true) to the paired SimulationBody objects (see picture e.g. AC, AB)

![grafik](https://user-images.githubusercontent.com/34217758/86462596-1fec1e00-bd2c-11ea-8384-f3969891e15a.png)

2. Extension of the 'CollisionAdapter' the following way

```

public class MinimumDistanceListener extends CollisionAdapter

. . .

	/** The {@link SimulationBody} which needs to be checked */
	private SimulationBody simulationBodyA;

	/** The {@link BodyFixture} which represents the base shape */
	private BodyFixture baseBodyFixtureA;

	/** The {@link BodyFixture} which needs to be checked with regard to the distance */
	private BodyFixture distanceBodyFixtureA;

	/** The other {@link SimulationBody} which needs to be checked */
	private SimulationBody simulationBodyB;

	/** The other {@link BodyFixture} which represents the base shape */
	private BodyFixture baseBodyFixtureB;

	/** The other {@link BodyFixture} which needs to be checked with regard to the distance */
	private BodyFixture distanceBodyFixtureB;

        ...

@Override
	public boolean collision(Body body1, BodyFixture fixture1, Body body2, BodyFixture fixture2, Penetration penetration)
	{
		// Cases for identification
		boolean caseA = (body1 == this.simulationBodyA && body2 == this.simulationBodyB);
		boolean caseB = (body1 == this.simulationBodyB && body2 == this.simulationBodyA);

		// The bodies can appear in either order
		if (caseA || caseB)
		{
			/**
			 * Define the different cases -> 4 in total
			 */
			boolean case1 = (fixture1 == this.baseBodyFixtureA) && (fixture2 == this.distanceBodyFixtureB);
			boolean case2 = (fixture1 == this.distanceBodyFixtureB) && (fixture2 == this.baseBodyFixtureA);
			boolean case3 = (fixture1 == this.baseBodyFixtureB) && (fixture2 == this.distanceBodyFixtureA);
			boolean case4 = (fixture1 == this.distanceBodyFixtureA) && (fixture2 == this.baseBodyFixtureB);

			if (case1 || case2 || case3 || case4)
			{
				// Here a collision is happening
				System.out.println("Collision is happening!");

				// Check the "importance" of SimulationBody (mass)
				Mass massA = body1.getMass();
				Mass massB = body2.getMass();

				// A more important than B
				if(massA.getMass() > massB.getMass())
				{
					
				}
				// B more important than A
				else if(massA.getMass() < massB.getMass())
				{
					
				}
				// Equally important A = B
				else
				{
					
				}
				
				// Testing behaviour
				//this.simulationBodyA.setActive(false);
				//this.simulationBodyB.setActive(false);
			}
		}
		return true;
	}

```

**Other approach:**

I think there is also the possibility to define different FilterCategorys but this will get quick very complex based on the undefined amounts of SimulationBody objects and several other aspects.

**Problem which needs to be solved:**

As you can see above I differentiate between the importance of SimulationBody objects based on their Mass.

Now I want, that for the below example (see picture) more or less the "basic" collission methods should run, but based on the Fixture "AC" of the first identified SimulationBody. 

![grafik](https://user-images.githubusercontent.com/34217758/86463461-d8669180-bd2d-11ea-83d0-2e27336a9c2f.png)

- SimulationBody A is moving towards SimulationBody C

- SimulaitonBody A has a higher mass than SimulationBody C

- SimulationBody A should move further in its desired direction and should also move SimulationBody C

---

Hope you can understand my problem.

As usual: If you need additional information I will provide them as soon as possible.

Thanks in advance :)

Best regards,

Carsten

**Comment by wnbittle** [comment]
I understand that you can't use the DistanceJoint because it doesn't maintain a distance between two bodies in the way you are looking for, but after that I was a little lost.  If you need to know the distance between any two fixtures, you can use a [DistanceDetector](https://github.com/dyn4j/dyn4j/blob/master/src/main/java/org/dyn4j/collision/narrowphase/DistanceDetector.java) like [GJK](https://github.com/dyn4j/dyn4j/blob/master/src/main/java/org/dyn4j/collision/narrowphase/Gjk.java).  This will give you an accurate [Separation](https://github.com/dyn4j/dyn4j/blob/master/src/main/java/org/dyn4j/collision/narrowphase/Separation.java) (with closest points) between the two bodies.

**Comment by DubWa91** [comment]
> If you need to know the distance between any two fixtures, you can use a DistanceDetector like GJK. This will give you an accurate Separation (with closest points) between the two bodies.

Thank you for that hint. This I will need for another part of my program :)

---

I try to rephrase my problem because I think I missed some points.

1. I have several SimulationBody in my World (e.g. A, B and C)

2. They can have "relations" (not Joints) to each other. In my case they should maintain a specific minimum distance to each other BUT they can be as far as they want from each other (Therefore no Joint relation). For an example please see the table/picture.

![grafik](https://user-images.githubusercontent.com/34217758/86530242-573b0600-beb7-11ea-8750-bff8fcc45ca7.png)

3. This means, that they can move around in the World and push or reflect each other (normal physics with forces etc.)

4. Now when 2 SimulationBody come close to each other, then should interact. But instead of the "main" BodyFixture (no sensor) they should act/resolve the collission with the additional "DistanceDetectionFixture" (is sensor). Please see the picture below (e.g. AC, AB)

![grafik](https://user-images.githubusercontent.com/34217758/86530332-37f0a880-beb8-11ea-9355-a03e56320938.png)


**Example 1**

**Comment by DubWa91** [comment]
Hi William,

since the 4.0.0 version is released I wanted to "push" that issue.

Is it now possible to include a `SimulationBody` with a sensor `BodyFixture`s into the collsion resolving (after detecting a specific collision => see description above about different `BodyFixture` types)?

---

I also noticed, that in the new version the `Sensed – A contact exists between a sensor body and another body` method of `ContactAdapter` is no longer available.

My assumption was, that I can achieve my desired behaviour with that method. What do you mean?

**Comment by DubWa91** [comment]
Update:

I checked the homepage and the described workflow of the engine again, and could identify (hopefully) a possible approach to achieve my desired behaviour.

---

![grafik](https://user-images.githubusercontent.com/34217758/93367928-7954eb00-f84d-11ea-8159-db1c420036cc.png)

Basically I have to add a `CollisionAdapterListerner` for one `BodyFixture` (sensor).

Then I have to check if I have (for example) a collision of the sensor `BodyFixture` of `SimulationBody` A and the "base" `BodyFixture` of `SimulationBody` B.

In the end I have to add a `Contact` in the `ContactManager`, which should be resolved (even if the one detected `BodyFixture` is a sensor).

But now with the new structure of `4.0.0` I am a bit lost because a lot of classes and methods are deprecated.

---

I think I have to modify the method [`processCollisions(Iterator<V> iterator)`](https://github.com/dyn4j/dyn4j/blob/87e741cbeea30e879d89a32bd020c72cbf0439fe/src/main/java/org/dyn4j/world/AbstractPhysicsWorld.java#L1213)

And here specifically the following lines

```
// add it to a list of contact-constraint only collisions for
// quicker post/pre solve notification if it's enabled and
// not a sensor collision
if (cc.isEnabled() && !cc.isSensor()) {
	this.contactCollisions.add(collision);
}
```

From my understanding, even if I could handle to add a `Collision` of a sensor `BodyFixture` with a "normal" `BodyFixture` I will fail at passing this.

---

My problem is, that I don't want to modify some methods of the source code for update reasons.

Is there a possibility to reach my desired behaviour only with some listeners?

Because I think I "only" have to add a sensor contact to a specific processing list...

Hopefully I didn't confuse you that much :-)

**Comment by wnbittle** [comment]
That particular diagram is out of date now, but it's close.

The `contactCollisions` list is only used for `preSolve `and `postSolve `notification.  Both sensor and disabled contacts will still participate further in the pipeline.  You could use the `StepListener.begin` method to iterate all contact constraints and change the enable/senor flags.

For example:
```java
StepListener<Body> sl = new StepListenerAdapter<Body>() {
  @Override
  public void begin(TimeStep step, PhysicsWorld<Body, ?> world) {
    Iterator<?> it = world.getCollisionDataIterator();
    while (it.hasNext()) {
      WorldCollisionData<Body> data = (WorldCollisionData<Body>)it.next();
      if (...) {
        data.getContactConstraint().setEnabled(true);
        data.getContactConstraint().setSensor(false);
      }
    }
  }
};
world.addStepListener(sl);
```

Looking through this I could see it being useful to have the `collision(ContactConstraint)` notification again.  Its a long story as to why I took that hook out.  Another thing I noticed is that the `StepListener` methods could be defined better to remove the casting.

**Comment by DubWa91** [comment]
Hi William,

thank you sooo much. It works pretty good and is exactly what I wanted :-)

---

Unfortunately I have to report a possible new bug in this context.

![collision_with_link](https://user-images.githubusercontent.com/34217758/93708785-61c17f00-fb39-11ea-8959-6d55d73a6eb4.gif)

As you can see in my attached GIF, a `SimulationBody` slides at a `Link` (Border) and later even slides through it.

This happens sometimes also with other shaped `SimulationBody`s with different `LinearVelocity`s (note: I don't apply `LinearDamping` and my worlds are always with no gravity).

My (layout) border I create the following way
```
// Setup the Points to define the layout
List<Vector2> borderPoints = new ArrayList<Vector2>();
Vector2 pointA = new Vector2(0.0, 0.0);
borderPoints.add(pointA);
Vector2 pointB = new Vector2(2.4, 0.0);
borderPoints.add(pointB);
Vector2 pointC = new Vector2(2.4, 1.6);
borderPoints.add(pointC);
Vector2 pointD = new Vector2(0.0, 1.6);
borderPoints.add(pointD);

// Create the layout
List<Link> borderpointLinks = Geometry.createLinks(borderPoints, true);

SimulationBody layoutBorder = new SimulationBody();
for (Link link : borderpointLinks)
{
	layoutBorder.addFixture(link);
}
layoutBorder.setMass(MassType.INFINITE);
layoutBorder.setColor(Color.BLACK);
```

**Comment by wnbittle** [comment]
Yeah, that appears to be a bug in the Geometry.createLinks method when setting closed = true.  I'll add an issue to get this resolved.  In the meantime, you could build the links manually:

```java
Vector2 pointA = new Vector2(0.0, 0.0);
Vector2 pointB = new Vector2(2.4, 0.0);
Vector2 pointC = new Vector2(2.4, 1.6);
Vector2 pointD = new Vector2(0.0, 1.6);

Link l1 = new Link(pointA, pointB);
Link l2 = new Link(pointB, pointC);
Link l3 = new Link(pointC, pointD);
Link l4 = new Link(pointD, pointA);

l1.setNext(l2);
l2.setNext(l3);
l3.setNext(l4);
l4.setNext(l1);

SimulationBody layoutBorder = new SimulationBody();
layoutBorder.addFixture(l1);
layoutBorder.addFixture(l2);
layoutBorder.addFixture(l3);
layoutBorder.addFixture(l4);
```

The other thing I would mention is that I would not use Links for this purpose.  If you need to contain objects to a certain area, use shapes with area to ensure objects don't tunnel their way out when traveling fast.

**Comment by DubWa91** [comment]
> Yeah, that appears to be a bug in the Geometry.createLinks method when setting closed = true.

Thank you. With your above mentioned method it detects the collision correctly :-)

>  If you need to contain objects to a certain area, use shapes with area to ensure objects don't tunnel their way out when traveling fast.

Thank you also for that hint. I will consider this as well.

PS: And sorry that I bother you that much with my questions (and bug reporting)

**Comment by wnbittle** [comment]
Awesome, glad that worked for you.  It's not a problem at all - bug reporting and questions help everyone.  I look at it as contributing.
