### ISSUE TITLE
Enhancement: Allow loop above listener

### ISSUE THREAD

**Issue by DubWa91** [dyn4j/dyn4j#120]
So far with the original class `World` there is no possibility to loop above all set `Listener` and do further actions.

Is there a reason for that implementation?

---

Background:

I wanted to remove all set `Listener` exept a specific class.

And because it isn't possible to loop above all `Listener` and check their class I had to do the following work-around.

```
/*
* Remove all Listener from the world, exept OutOfBounds
* 1) get OutOfBounds listener (LayoutBoundsListener)
* 2) remove all listener
* 3) add again the the OutOfBounds listener
* No function available to loop above all existing listener
 */
ArrayList<LayoutBoundsListener> layoutBoundsListeners = (ArrayList<LayoutBoundsListener>) this.world.getListeners(LayoutBoundsListener.class);
this.world.removeAllListeners();
for (LayoutBoundsListener layoutBoundsListener : layoutBoundsListeners)
{
	this.world.addListener(layoutBoundsListener);
}
```

---

I know, that I could also modify the class `World` but I want to use as much as possible your latest versions (library for a clean workspace) and only extend classes that are really needed for my program,

**Comment by wnbittle** [comment]
Unfortunately, 4.0.0 is going to be removing this feature entirely.  The World.getListeners(Class<T>) method was originally done out of convenience because I didn't want to create 8 different lists internally, one for each listener type.  It turns out that this was a mistake - it's slower, difficult to understand, didn't fit with the rest of the API, and limited the API in the end.

In 4.0.0 for example, to add/remove a listener you'll need to call the appropriate add/remove method: addBoundsListener, removeBoundsListener, removeAllBoundsListeners.  

Can you explain a little bit more about the reason you are mass removing listeners based on type?

**Comment by DubWa91** [comment]
> In 4.0.0 for example, to add/remove a listener you'll need to call the appropriate add/remove method: addBoundsListener, removeBoundsListener, removeAllBoundsListeners.

Okay thanks for the information. This will also be suitable for me.

> Can you explain a little bit more about the reason you are mass removing listeners based on type?

Basically I have a program where I have a static layout (layout borders,, interfering contours, etc.) with `MassType.INFINITE`.

To that static layout I apply some `Listener`s which are only for these static objects.

Then I have several runs, where I add different `SimulationBody`s to the static layout each run and therefore different `Listener` for condition motintoring or KPI calculations (maybe this explains a little bit my previous questions :) ).

After each run I only want to delete the new added "dynamic" objects and their listener.

```
// Setup the static layout objects (border, input/output, interferingcontour)
layoutSimulation.initializeLayout();
		
// Get the generated solutions
ArrayList<ObjectList> listsToPlace = this.contentManager.getSolutionManager().getAssemblyLineSolutions();
		
// Loop over the generated solutions
for (ObjectList objectList : listsToPlace)
{
	// Model dynamic bodies
	layoutSimulation.modelObjects(objectList);
			
	// Place dynamic bodies
	layoutSimulation.placeObjects(objectList);
			
	// Loop for equilibrium
	layoutSimulation.loop();
		
	// Clear the dynamic world before proceed with the next solution
	layoutSimulation.clearWorld();
}
``` 

---

I hope that helps to understand :)
