### ISSUE TITLE
Are there any Geometry file changes since 3.4.0?

### ISSUE THREAD

**Issue by gkjpettet** [dyn4j/dyn4j#128]
Congratulations on the new release of Dyn4j. I’ve been slowly porting 3.4.0 to Xojo. I’ve so far only managed to port all the contents of the `geometry` folder. 

I see that there are a lot of performance increases in version 4 that’s just released. Were any changes made to the geometry files because if they haven’t changed I’ll switch to porting version 4 instead. I’m just nervous about switching mid port because whilst I understand the code I don’t understand the physics logic or maths!

Many thanks for this work. It’s really cool and it’s the only physics engine that I’m able to port to Xojo because of the similarities between Xojo and Java.

**Comment by gkjpettet** [comment]
FYI @wnbittle, I tried to email you at your dyn4j.org email address but I got a "mailbox full" error and the message was undelivered. I wasn't sure if you were aware.

**Comment by wnbittle** [comment]
@gkjpettet Yes, there were changes, though they should be minimal.  I remember adding a new method for creating an AABB but using the one given to the method instead returning a new one.  I think there were a few more methods added to the AABB class, a few methods added to the Matrix22 class, and a few bug fixes in the Transform class.

In the future I'm planning to segment these changes into individual PRs to help with things like this (sorting through a giant update is never fun).

**Comment by gkjpettet** [comment]
Thanks @wnbittle for clarifying. Sounds like the changes are minor and your tests are excellent. I think I’ll switch to porting the new 4.0 branch after updating the geometry files I’ve already ported. 

The only test that is currently failing for me is the robust geometry one. That’s a hard one for me to get my head around.
