### ISSUE TITLE
BayazitTest.nsoftTriangulateFailure

### ISSUE THREAD

**Issue by gkjpettet** [dyn4j/dyn4j#132]
I'm porting dyn4j to Xojo.

I've currently ported almost all of the geometry package (just the decompose files to go) and all tests are passing. 

I'm working on the Bayazit tests and they all pass except for the last one: `nsoftTriangulateFailure`. I'm getting the equivalent of a Java `IllegalArgumentException` when validating a polygon within the `Bayazit.DecomposePolygon`.

I'm pretty sure I know the answer to this question but before I start diving into my code can I check that this test is supposed to pass without raising an `IllegalArgumentException`? The test is named `nsoftTriangulateFailure` and I'm hoping that it's supposed to fail rather than pass (in which case my code is OK).

**Comment by wnbittle** [comment]
The test passes in Java.  I'm guessing (it's been a while) that the test _was_ broken, until the fix was applied and should now run successfully.

**Comment by gkjpettet** [comment]
Thanks @wnbittle. 
I found the bug (in my code). Since Xojo has no `Signum` function I had to write my own and the test found a case where my function returned `1.0` instead of `0`  I adjusted my tolerance and it passes successfully.
