### ISSUE TITLE
How to replace Body.isInContact(Body2)

### ISSUE THREAD

**Issue by ia97lies** [dyn4j/dyn4j#143]
For an easy peasy collision detection (where I'm not interested at which point or angle) I have this piece of code

    public static boolean isColliding(final Dyn4jBody b1, final Dyn4jBody b2) {
        if (b1 != null && b2 != null && !b1.equals(b2)) {
            return b1.isInContact(b2);
        }
        return false;
    }

Is there a simple replacement for this?

**Comment by wnbittle** [comment]
That method (and a few others listed below) moved to the World class.  The replacement is `world.isInContact(b1, b2);`

- `Body.getContacts(boolean)` is now `PhysicsWorld.getContacts(T)`
- `Body.getInContactBodies(boolean)` is now `PhysicsWorld.getInContactBodies(T, boolean)`
- `Body.getJoinedBodies()` is now `PhysicsWorld.getJoinedBodies(T)`
- `Body.getJoints()` is now `PhysicsWorld.getJoints(T)`
- `Body.isConnected(Body)` is now `PhysicsWorld.isJoined(T, T)`
- `Body.isConnected(Body, boolean)` is now `PhysicsWorld.isJointCollisionAllowed(T, T)`
- `Body.isInContact(Body)` is now `PhysicsWorld.isInContact(T, T)`

**Comment by ia97lies** [comment]
Thanks a lot for the very fast reply. That helps, I'm close to finish the upgrade. One more question to the RayCast, in the past I could register a raycast filter to for example ignore in a ray cast. Do you have a replacement for this as well?

**Comment by wnbittle** [comment]
Yep.  The last argument to the `world.raycast` methods is a `DetectFilter<T,E>`.  This is the replacement for the listener.  For example:

```java
world.raycast(ray, 10.0, new DetectFilter<Body, BodyFixture>(false, true, null));
```

You could also sub-class the DetectFilter and override the isAllowed method as before.

```java
class MyDetectFilter extends DetectFilter<Body, BodyFixture> {
  public MyDetectFilter() { 
    super(false, true, null); 
  }
  public boolean isAllowed(Body body, BodyFixture fixture) {
    boolean allowed = super.isAllowed(body, fixture);
    // your custom logic
    allowed &= ...
    return allowed;
  }
}
static DetectFilter<Body, BodyFixture> raycastFilter = new MyDetectFilter();
world.raycast(ray, 10.0, raycastFilter);
```

**Comment by ia97lies** [comment]
cool, thanks a lot :)

**Comment by wnbittle** [comment]
Is there a reason you wanted `DetectFilter<Body, Fixture>` instead of `DetectFilter<Body, BodyFixture>`?  If T is `Body`, E must be `BodyFixture` or a subclass of it.

**Comment by ia97lies** [comment]
No BodyFixture is fine. I managed it now :) Works as intended. And I can profit from the performance boost of this amazing physics engine.
