### ISSUE TITLE
How to upgrade BroadphasePair to new version

### ISSUE THREAD

**Issue by Pesegato** [dyn4j/dyn4j#144]
This is my code, which worked until today:

```
            List<BroadphasePair<Body, BodyFixture>> pairs = bp.detect();
            for (BroadphasePair<Body, BodyFixture> pair : pairs) {
                Body body1 = pair.getCollidable1();
                Body body2 = pair.getCollidable2();
```

You might ask: "Why aren't you using World?", so I point you to the relevant forum thread.

http://forum.dyn4j.org/viewtopic.php?f=1&t=297

Thanks!

**Comment by wnbittle** [comment]
There are a couple of options available in 4.x.  If you want to keep your code the same, simply use the `CollisionPair<Body, BodyFixture>` interface.

The physics/collision detection pipelines have been separated now into two interfaces `CollisionWorld` and `PhysicsWorld`.  You could implement the `CollisionWorld` interface by extending the `AbstractCollisionWorld` class if that would be better:

```java
class MyCollisionWorld extends AbstractCollisionWorld<Body, BodyFixture, WorldCollisionData<Body>> {
	@Override
	protected WorldCollisionData<Body> createCollisionData(CollisionPair<Body, BodyFixture> pair) {
		return new WorldCollisionData<>(pair);
	}
	@Override
	protected void processCollisions(Iterator<WorldCollisionData<Body>> iterator) {
		while (iterator.hasNext()) {
			WorldCollisionData<Body> data = iterator.next();
			// TODO do something with the collisions found
		}
	}
}
```
