### ISSUE TITLE
Storing AABB with jackson leads to recursive loop

### ISSUE THREAD

**Issue by ia97lies** [dyn4j/dyn4j#147]
I try to store my entity components. One of the components does contain the AABB class from dyn4. Storing that class leads to a recursive loop because of a reference chain

"boundary":{"minX":48.5,"minY":-35.0,"maxX":50.0,"maxY":-31.0,"area":6.0,"perimeter":11.0,"degenerate":false,"center":{"x":49.25,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,"ycomponent":{"x":0.0,"y":-33.0,

any thoughts on this? I will solve this for now by not storing the AABB in my components but just storing the corners. But would be nice if it's storable. I guess.

**Comment by wnbittle** [comment]
There shouldn't be any reference chain as part of the AABB class.  It has 4 members all of which are primitive doubles.  Are you sure that's the dyn4j [AABB](https://github.com/dyn4j/dyn4j/blob/master/src/main/java/org/dyn4j/geometry/AABB.java) class?

**Comment by ia97lies** [comment]
com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->....->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"]->org.dyn4j.geometry.Vector2["ycomponent"])
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)

The boundary is in this class which I store

package ch.artificials.bubble.es;

import com.simsilica.es.EntityComponent;
import org.dyn4j.geometry.AABB;

public class LevelExit implements EntityComponent {

    private final AABB boundary;
    private final String nextLevel;
    private final String type;

    public LevelExit() {
        this(new AABB(0), "", "");
    }
    
    public LevelExit(AABB boundary, String nextLevel, String type) {
        this.boundary = boundary;
        this.nextLevel = nextLevel;
        this.type = type;
    }

    public AABB getBoundary() {
        return boundary;
    }

    public String getNextLevel() {
        return nextLevel;
    }
    
    public String getType() {
        return type;
    }
    
    @Override
    public String toString() {
        return getClass().getSimpleName()
                + ", boundary=" + boundary 
                + ", nextLevel=" + nextLevel 
                + ", id=" + type + "]";
    }

}

I don't know from where this center vector is coming. O do I maybe have a too old version of dyn4j?

**Comment by ia97lies** [comment]
I had to completely remove the AABB from my component and when I read the component, I transform the data to an dyn4j AABB on the fly. I really don't get it. As you said there are only for member variables. But somehow jackson seems to have a problem storying dyn4j.Vector2 objects even I have no clue from where this vector is coming from.

I have a workaround for now.

**Comment by wnbittle** [comment]
I think what's happening here is that Jackson is trying to serialize everything that matches the pattern `get*`.  For example, in the first output you posted, it serializes the `min`/`max` values, but then also serializes something called "center".  Center is not a field, but there is a getter named `getCenter`.

Since you probably don't want to fork the library and add Jackson serialization and I don't want to add a dependency to the library, your best bet is to define a [mixin](https://stackoverflow.com/a/28173019), a [custom serializer](https://stackoverflow.com/a/28174119), or find a [set of configuration options](https://stackoverflow.com/a/28172878) that work.

**Comment by ia97lies** [comment]
thanks a lot for your pointers, I guess I have to look into custom serializers. I spot some more problems which I probably can easily mitigate with that approach.
