### ISSUE TITLE
SimulationBodies overlap after DistanceJoint applied

### ISSUE THREAD

**Issue by DubWa91** [dyn4j/dyn4j#157]
Hi William,

I have the following szenario:

1) 3 different areas modelled as `SimulationBody` with `MassType.INFINITE` and applied `CategoryFilter`
2) Circular `SimulationBody`s: All with the same mass but different sizes. These `SimulationBody`s are arranged in the specific areas (see picture). And also applied `CategoryFilter` so that they collide with each other (in the same area) and with the different borders (overall border -> red, border to other areas) => **This works I tested it with randomly set velocities to specific `SimulationBody`s**
3) I wait, till there is no longer an overlapping of defined `SimulationBody`s (in that case all circular `SimulationBody`)
4) I apply `DistanceJoint`s to `SimulationBody`s => Not all are connected with each other but one `SimulationBody` can have several relations/connections (see gif)

---

Material:

![grafik](https://user-images.githubusercontent.com/34217758/97583075-d02a1480-19f6-11eb-837e-01603564983d.png)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34217758/97584176-0916b900-19f8-11eb-833f-7690beafd82e.gif)

---

Problem:

After the `DistanceJoint`s are applied, the 2 `SimulationBody`s from area 3 also move to area 1 and overall a lot of `SimulationBody`s start to overlap with each other so that it is not possible to reach a system equilibrium (no movement).

---

My goal:

The connected `SimulationBody`s should move as close together as possible without overlapping because my idea is, that the system can rearrange itself automatically and that the `SimulationBody` will find their position based on all relations.

---

What I tested:

*  The category filter are working
*  Connected `SimulationBody`s will find their equilibrium even when there is a `SimulationBody` inbetween them (for example if another connection could come closer together in a faster way e.g. based on initial distances etc.) and the `DistanceJoint` could reach the defined rest length (`setDistance()`)

![Spring_reach_equilibirum](https://user-images.githubusercontent.com/34217758/97586046-1a60c500-19fa-11eb-90ff-77ce304d2327.gif)

*  I also set the circular `SimulationBody` to bullet, in case the instant applied `DistanceJoint`s cause to much velocity

---

My questions:

*  Do you have any idea what could cause the problem with the tunneling?
*  Is it possible to change the "anti-penetration" forces to solve overlapping?
*  Do you have any other idea how I can achieve my goal with self-arranging `SimulationBody`s?

---

Every hint is appreciated :)

Thank you in advance. If you need more information please let me know.

**Comment by dlwaters** [comment]
I'm totally new to dyn4j but here's a few ideas based on work with Box2d,
liquidfun and such.

1) If the distance joints are springs, reduce the tension on the spring.
They snap together very aggressively.  I don't yet understand "frequency"
vs "damping" in dyn4j so here's a note from the Javadocs:

This joint doubles as a spring/damper distance joint where the length can
change but is constantly approaching the target distance. Enable the
spring/damper by setting the frequency and damping ratio to values greater
than zero. A good starting point is a frequency of 8.0 and damping ratio of
0.3 then adjust as necessary.

https://www.javadoc.io/doc/org.dyn4j/dyn4j/latest/org.dyn4j/org/dyn4j/dynamics/joint/DistanceJoint.html


2) Increase the distance between joints until the system functions.  Then
slowly reduce that distance until it fails again. (You don't mention max
radius vs joint distance so I have a concern that you might be forcing
items too close together.)

3) Start with only single-connections to see if the items with connections
to more than one object are causing the issues.  Especially with adding the
joints all of a sudden, I can see multiple joints on tightly packed objects
behaving unpredictably.

4) Increase the height of the outer box so there isn't downward pressure on
the system.  Currently, your tangle of objects is constrained on 3 sides.
The combination of "pressure" from 3 sides may be accelerating the
collapse.

5) Reduce the size of your largest circles until the system functions.  You
have circles that are very close to 50% height.  Notice the way your test
with an object between your two joined objects.  The circle entity pulls
*inside* the object briefly  If you have 3 large circles nearly stacked
when you yank things together, my guess is you might be pulling the
exterior edge of a circle past the center of some other circle.  I imagine
that might cause the joint to fail.

6) Try polygon shape instead of circle.  The polygon in your test with the
object in between, the polygon doesn't penetrate the in between object.

And, finally ... test with fewer objects!  It is tempting to go for the
gusto when designing but when things go wrong, simplify.

I hope some of this helps.

Dean

**Comment by wnbittle** [comment]
Self-arranging is a [study](https://www.diva-portal.org/smash/get/diva2:811085/FULLTEXT01.pdf) in itself is my understanding.  Doing this with dyn4j might work, but it will be all about getting the settings right.  Can you try something like the following:

```java
DistanceJoint<Body> dj = ...
// all joints by default do not allow collision, but in this case we need it
dj.setCollisionAllowed(true);
// set the target distance to zero
dj.setDistance(0);
// set the frequency low (this reduces the forces used to bring them together)
dj.setFrequency(1);
// set the damping ratio to high (this reduces the bouncing)
dj.setDampingRatio(0.7);
```

This worked in my tests with and without gravity enabled.

**Comment by dlwaters** [comment]
William,

I'm very excited to have found your physics engine.  I started doing
simulations in Processing using JBox2d and LiquidFun but much of the code
hasn't been updated in years and some crashes were driving me nuts.  dyn4j
seemed to me to be the only lightweight, currently maintained
implementation I could find.  And your code documentation is great. I'm
thrilled!

Your explanation of distance joints helped me a lot, especially the
distance zero and frequency/damping explanations.

Is there a reason spring "tension" is called frequency?  Is that like
frequency of a directional impulse used to emulate tension, or
something like that?

Dean

**Comment by DubWa91** [comment]
First of all thank you both very much for your answers :-) 

---

> 1) If the distance joints are springs, reduce the tension on the spring. They snap together very aggressively.  I don't yet understand "frequency" vs "damping" in dyn4j so here's a note from the Javadocs:

They snap together so aggressivly because of the maybe huge difference of the current distance and the set target distance.
I also tested different settings for `frequency` and `damping ratio`. I think the problem here is really the distance because in my example I have several meters(!)

---

 > 2) Increase the distance between joints until the system functions.  Then
slowly reduce that distance until it fails again. (You don't mention max
radius vs joint distance so I have a concern that you might be forcing
items too close together.)

Currently I have set the target distance between 2 joined `SimulationBody` to the sum of their radii (radius) -> intention is, that they then move as close together as possible.

I already have some code (listener) which can achieve what you describe. I will apply it to my use-case. Thank you for reminding me of that :)

---

>3) Start with only single-connections to see if the items with connections
to more than one object are causing the issues.  Especially with adding the
joints all of a sudden, I can see multiple joints on tightly packed objects
behaving unpredictably.

I will also test this one.

---

> 4) Increase the height of the outer box so there isn't downward pressure on
the system.  Currently, your tangle of objects is constrained on 3 sides.
The combination of "pressure" from 3 sides may be accelerating the
collapse.

I have to maintain these boxes (these are constraints). But maybe I can try to relax this, and then after they are arranged I can add again the top-box which forces the `SimulationBody` to arrange themself in the width of the area. 

---

> 5) Reduce the size of your largest circles until the system functions.  You
have circles that are very close to 50% height.  Notice the way your test
with an object between your two joined objects.  The circle entity pulls
*inside* the object briefly  If you have 3 large circles nearly stacked
when you yank things together, my guess is you might be pulling the
exterior edge of a circle past the center of some other circle.  I imagine
that might cause the joint to fail.

That is a very good point. Thank you. Didn't notice it.

---

> 6) Try polygon shape instead of circle.  The polygon in your test with the
object in between, the polygon doesn't penetrate the in between object.

I will also test this approach.

---

> And, finally ... test with fewer objects!  It is tempting to go for the
gusto when designing but when things go wrong, simplify.

:-) You are totally right. I often make this mistake :-(

---
---

> Self-arranging is a study in itself is my understanding.

Thank you for that paper. I will have a look.

---

> Can you try something like the following:

```
DistanceJoint<Body> dj = ...
// all joints by default do not allow collision, but in this case we need it
dj.setCollisionAllowed(true);
// set the target distance to zero
dj.setDistance(0);
// set the frequency low (this reduces the forces used to bring them together)
dj.setFrequency(1);
// set the damping ratio to high (this reduces the bouncing)
dj.setDampingRatio(0.7);
```

>This worked in my tests with and without gravity enabled.

I will try this and provide feedback. Thank you.

Could you reach a system equilibrium? And did you had also the same workflow? That means, that you also apply the `DistanceJoint`s very spontaneous or did you set all in the `initializeWorld()` method?

**Comment by DubWa91** [comment]
Update:

I could make it run (at least now the overlapping problem is solved) :-)

The problem was caused because sometimes I set the frequency of some `DistanceJoint`s to `0.0`.

I define a ratio of 2 random `integer` and when the value is 0.0 then this ratio will be multiplied with a global set frequency.

With that approach I want to define different "strengths" of attraction.

But I also tried the approach with the polygonal circle, which is also suitable for my goal.

Thank both you very much for your hints and suggestions :-) Now it's up to me to define a suitable termination criteria

**Comment by wnbittle** [comment]
@DubWa91 glad to hear.

@dlwaters In short, the frequency is the oscillation period (in hertz) - how many times per second should the spring be oscillating around the rest position.  Naturally, the damping coefficient will slow it down.

The [equation](https://en.wikipedia.org/wiki/Hookes_law#Harmonic_oscillator) f = 1 / (2π) * sqrt(k / m), can be rewritten as  k = m(2πf)^2.  The implication is that if the mass of the body changes and the frequency is constant, the spring constant must change.  On the flip side, if the mass of the body changes and the spring constant is constant, the frequency must change.  The former seemed more stable from a user perspective - in other words, if you had a spring between two bodies and you modified one of those bodies to have more mass, the oscillation frequency would stay the same and the spring constant would automatically be adjusted.

**Comment by dlwaters** [comment]
That makes makes good sense and I think it was a good choice.

Your code is so cleanly written and documented that I was pretty sure
frequency was a deliberate naming choice. Knowing (intuitively) what is
behind the name helps me understand and remember it's function.

Many coders are not so kind in their naming conventions!
