### ISSUE TITLE
Samples: SimulationBody extends Body ... Body is deprecated?

### ISSUE THREAD

**Issue by dlwaters** [dyn4j/dyn4j#158]
SimulationBody.java in samples:

18: public class SimulationBody extends Body 

I'm using intelliJ so if I use strange terminology, that might explain it.

I followed "Body" back to its declaration and found this in Body.java:

`@SuppressWarnings("deprecation")
public class Body extends AbstractPhysicsBody implements PhysicsBody, CollisionBody<BodyFixture>, Transformable, DataContainer, Ownable {
	/** 
	 * The {@link Body}'s contacts
	 * @deprecated Deprecated in 4.0.0. No longer needed.
	 */
	@Deprecated`

If Body is deprecated, should this be updated to the new class in Samples? 

More important for me; If Body is deprecated, what class should be used instead?  I'm trying to understand the code behind the code. 

Thanks.

**Comment by wnbittle** [comment]
@dlwaters The org.dyn4j.dynamics.Body class is NOT deprecated.  There ARE deprecated members (fields, methods, etc) though.  That annotation is there to suppress warnings about deprecation internally.  You'll still get the proper deprecation warning if you try to use a deprecated member from your code.

**Comment by dlwaters** [comment]
Okay ... sorry about that.  My bad.

I scrolled through the code quickly and didn't see that the constructor
itself wasn't deprecated.  I still have a lot to learn about Java.
