### ISSUE TITLE
Collision with infinite mass type bodies while dragging

### ISSUE THREAD

**Issue by Flygir** [dyn4j/dyn4j#164]
When i drag a body with normal mass type over a other body with normal mass type they collide. But when i drag the same body with normal mass type over a body with infinte mass type (a wall or something similar) they don't collide. 

So my question is how can i set collision between a normal mass type body and a infinte mass type body while i drag the body with normal mass type?

**Comment by wnbittle** [comment]
@Flygir  can you be more specific in HOW you are dragging the body?

**Comment by Flygir** [comment]
I work with JavaFX and listen to a MouseDrag Event on a JavaFX shape that is mapped to the body. So when I drag the Shape with my Mouse I set the shape and the body to the new coordinates given from the MouseDrag Event.

**Comment by wnbittle** [comment]
Take a look at https://github.com/dyn4j/dyn4j-samples/blob/master/src/main/java/org/dyn4j/samples/MouseDrag.java sample.  Here's another way https://github.com/dyn4j/dyn4j-samples/blob/master/src/main/java/org/dyn4j/samples/SimplePlatformer.java.  Not sure what type of control you need, but in general, setting the controlled body's transform will not work.
