### ISSUE TITLE
Balanced tree does not work properly for left-right and right-left cases

### ISSUE THREAD

**Issue by Goncalo-Marques** [dyn4j/dyn4j#298]
**Describe the bug**
Unless I am missing something in the implementation of the self-balancing binary tree, there is a problem with the left-right and right-left cases.

This problem occurs because of the if statement in `BinarySearchTree.java` when checking for left-right and right-left cases in the following function:
```java
BinarySearchTreeNode<E> balance(BinarySearchTreeNode<E> node)
```

As you may notice in the screenshot, when dealing with a left-right case, `ach` is equal to 1, so it will never be `ach > 1`, so the if statement that would change it to a left-left case will not be entered.
To fix this, it would be a matter of updating the if statement to:
```java
if (ach > 0) {
    [...]
}
```

**To Reproduce**

1. Create a self-balanced binary tree
2. Insert the integer 3
3. Insert the integer 1
4. Insert the integer 2

**Expected behavior**
The following tree should be created:
```
  2
 / \
1   3
```

**Actual behavior**
Instead, the following tree is created:
```
  1
   \
    3
    /
   2
```

**Screenshots/Videos**
![image](https://github.com/user-attachments/assets/8ffbb030-0afc-4b08-905f-c20b9e250819)

**Runtime Information:**
- dyn4j Version: 5.0.0 (7b09d1984d42ee845a5b58b8d86d8a9e805db36a)

**Additional context**
- The example provided is for a left-right case, but the same problem (and solution) is applicable to the right-left case
- As you can see in "Actual behavior", the tree is not balanced correctly
- As a suggestion, I would also add better test assertions to the binary tree insertion method
    - For example, by asserting the position of the inserted elements with respect to the root of the tree

**Comment by Goncalo-Marques** [comment]
As a side note, but also related to the binary tree.
I think the remove methods are not working as expected either.

The `removeMinimum()`, `removeMaximum()` and `removeNode()` functions/methods are not balancing the tree properly when the `selfBalancing` flag is true.

---

Also, `removeMinimum()` and `removeMaximum()` do not update the parent nodes of the children of the node being removed. 

Besides that, these functions seem to contain some unnecessary if statements. Taking the example of `removeMinimum()`, the following if statement (`if (node.parent.right == node)`) will never be true, since we already know that the node to be removed represents the minimum value of the tree, so it must always be a left child, respecting the definition of the binary tree data structure. This "problem" should also apply to `removeMaximum()`, but vice versa, since we already know that the maximum node will always be on the right side of its parent.
![image](https://github.com/user-attachments/assets/5ea0dd63-3cd0-4dc9-95c0-60ad0d0d3b96)

In my opinion, to solve these problems with `removeMinimum()` and `removeMaximum()`, we could simply find the node and then use the already existing `removeNode()` to remove the node. This would also make the code easier to maintain.
Taking the example of `removeMinimum()`, it would be something like this:
```java
	BinarySearchTreeNode<E> removeMinimum(BinarySearchTreeNode<E> node) {
		// check if the given subtree root node is null
		if (node == null) return null;
		// find the minimum
		node = this.getMinimum(node);
		// remove the node
		removeNode(node);
		// return the minimum
		return node;
	}
```

**Comment by wnbittle** [comment]
- [x] Thanks for the issue report.  This code is very old and I remember it was intentional to be appropriately balanced, but can't find the source that I built it from.  That said, I've been looking into the code and found the same issue (with remove).

I think a rewrite of this is in order and I've been working on the last few days.

**Comment by Goncalo-Marques** [comment]
> I think a rewrite of this is in order

That's nice, looking forward to it!

**Comment by wnbittle** [comment]
@Goncalo-Marques I've pushed a commit to the main branch fix this issue.  The good thing was that there was a lot of reuse with what I had before, but the insert/remove methods needed a complete rewrite.  I also added more relevant tests.

**Comment by Goncalo-Marques** [comment]
Thanks, I think I'll have a look tomorrow, then I'll close this ticket.

**Comment by Goncalo-Marques** [comment]
Small thing, but the documentation for the `AVLTree()` constructor is outdated.

**Comment by wnbittle** [comment]
Ahh good catch, I'll get that updated - really appreciate the review

**Comment by Goncalo-Marques** [comment]
No problem at all.
Thank you for this great project!

I am closing the issue now.
