### ISSUE TITLE
Quadratic complexity of island creation step

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#39]
While tweaking the dyn4j source I noticed a strange massive slowdown when adding beyond 5k bodies and things went horribly wrong beyond that. Performance scaled pretty well up to that, so something seemed of. After a bit of digging a bit I found that the step that resets static bodies to not being on an island has quadratic complexity and was the sole slowdown reason.

Luckily the fix is very easy and gives tremendous speedup when using a lot of bodies (I got like a 10x speedup just at 7k bodies with the fix)

The only change needed (in World.java:633) is to replace

```
for (int j = 0; j < size; j++) {
    Body body = this.bodies.get(j);
    if (body.isStatic()) {
        body.setOnIsland(false);
    }
}
```

with 

```int isize = island.bodies.size();
for (int j = 0; j < isize; j++) {
    Body body = island.bodies.get(j);
    if (body.isStatic()) {
        body.setOnIsland(false);
    }
}
```

**Comment by wnbittle** [comment]
Fixed in bc0d4433fa957837303b99729443f0166fecf3f3
