### ISSUE TITLE
AABB and Vector2

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#46]
The AABB class currently uses two vectors for representation. I suggest to change that to 4 doubles (same with before, just unpacked). The vectors add a level of indirection, increase memory and add extra work for the GC to do. This also helps for mobile/low end devices, since all AABB are created at each step etc.
I have tested this version and it also provides some speed benefits. If you are ok with such change William, please reply here and I'll make it into a pull request.

Thanks

**Comment by wnbittle** [comment]
Yeah, feel free to take a stab at it.

**Comment by symaxian** [comment]
I've only recently started utilizing dyn4j but this seems like a good change. Flattening data structures can be really easy performance wins, especially in a garbage collected language.

**Comment by mtsamis** [comment]
Yeah so it is, you can check https://github.com/dyn4j/dyn4j/pull/48 if interested which implements this and other things.
