### ISSUE TITLE
Strange computations in SequentialImpulse

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#53]
There are some calculations in SequentialImpulses::solvePositionContraints that look odd to me. Specifically in line 517 onwards
`// could be 1 or 0 if one object has infinite mass`
`double invMass1 = mass1 * m1.getInverseMass();`
`double invI1 = mass1 * m1.getInverseInertia();`
`// could be 1 or 0 if one object has infinite mass`
`double invMass2 = mass2 * m2.getInverseMass();`
`double invI2 = mass2 * m2.getInverseInertia();`

Why multiply all the inverse values with the masses? Apart from the fact that invMass1 will be 1 or 0 (as stated) which does not seems meaningful based on the computations below that code, the name also seems strange because that is not the inverse mass.
Sequential impulses where based on the corresponding contact solver from box2d, and after taking a look at it I saw it uses just the inverse values without multiplying by the masses.
Is this by accident or there's a reason for the multiplication?

**Comment by wnbittle** [comment]
At first glance this looks like a bug to me.

**Comment by mtsamis** [comment]
I also tried removing those while testing some things. I observed no major change in some sample simulations. Either way, I also thing the multiplications should not be there.
