### ISSUE TITLE
Fix possible bug in SAP

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#55]
After the new unit test for broad-phase detectors a possible bug in SAP#detect(AABB) was found and currently the master branch fails this test. I have not yet determined the cause of it, but we should have a look at it and fix this. I don't know if this is related somehow to the changes after https://github.com/dyn4j/dyn4j/issues/20.
You can add this for the 3.3.1 milestone as well.

**Comment by wnbittle** [comment]
I've found the problem.  The code is attempting to do a binary search to find a starting AABB for the query, but the tree is sorted to optimize the global detection routine and that sort won't work for AABB query or raycast optimizations like this.

The only option is to change the SAP AABB query and raycasting methods to O(n) which is no better than brute force.  I'll update the documentation to call this out, but it really reduces the utility of this particular broadphase.

**Comment by mtsamis** [comment]
I see, this is indeed the worst possible outcome. At least we have the rest broadphase detectors, so it shouldn't be a problem overall.
Since you've made the relevant commit already I'm closing this issue.
