### ISSUE TITLE
Raycast not hitting object

### ISSUE THREAD

**Issue by prat-man** [dyn4j/dyn4j#60]
I am trying to cast a ray onto the wall from the rectangle.
However, the ray is being stopped much before as evident from the following image.
It is as if there are invisible walls to the left and to the right.
I know I am probably missing some concept.
Can you please help me to get the raycast point to the wall?

![Raycast](https://user-images.githubusercontent.com/13336387/63026650-321d5d80-bec9-11e9-8fe8-6a19877f4930.png)

**Comment by prat-man** [comment]
I just did a little experiment. It seems if I make the lines slightly slanted, then ray-casting works properly again. Weird!

![Raycast_slanted](https://user-images.githubusercontent.com/13336387/63029304-ee792280-becd-11e9-918f-122718df4d42.png)

**Comment by wnbittle** [comment]
Can you supply a sample of the failure case (the shape types and coordinates and Ray details)?  I’d like to investigate further.

**Comment by prat-man** [comment]
The walls/track shape is derived from the SimulationBody class in the Sample program. It is made of a number fixtures made by Link objects:

```
List<Link> links = Geometry.createLinks(vertices, false);
for (Link link : links) {
	this.addFixture(link);
}
```

The variable vertices is an array of Vector2 objects with the following values:
```
0.0 0.72
-0.54 0.72
-0.56 0.71
-0.57 0.70
-0.58 0.68
-0.58 0.41
-0.59 0.39
-0.6 0.38
-0.97 0.38
-0.98 0.38
-0.99 0.37
-1.0 0.35
-1.0 0.0
-1.2 0.0
-1.2 0.5
-1.18 0.55
-1.16 0.57
-1.14 0.58
-0.8 0.58
-0.78 0.59
-0.77 0.61
-0.77 0.88
-0.76 0.9
-0.75 0.91
-0.73 0.92
0.0 0.92
```

The rectangular object represents a car which is present at point:
`-0.85 0.48`

The raycast is performed as follows.
Here track is a variable containing the track body object. Car is a variable containing the car body object (the small rectangular body from which all raycasts are made).
```
double[] angles = { 0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75 };

List<VisibleRay> visRayList = new ArrayList<>();

for (double angle : angles) {
	Ray ray = new Ray(car.getWorldCenter(), (car.getRotation() + angle) * Math.PI);
	
	RaycastResult result = new RaycastResult();
	
	boolean intersected = world.raycast(ray, track, 0, true, result);
	
	if (intersected) {
		sensors[index] = result.getRaycast().getDistance();
		
		VisibleRay visRay = new VisibleRay(car.getWorldCenter(), result.getRaycast().getPoint());
		
		visRay.setColor(randCol);
		
		visRayList.add(visRay);
	}
}

for (VisibleRay visRay : visRayList) {
	this.world.addBody(visRay);
}
```

VisibleRay is another class derived from SimulationBody in the Samples:
```
public class VisibleRay extends SimulationBody {
	
	private Vector2 start;
	private Vector2 end;
		
	public VisibleRay(Vector2 start, Vector2 end) {
		
		addFixture(new Link(start, end));
		
		setColor(Color.LIGHT_GRAY);
		
	}
	
	public Vector2 getStart() {
		return start;
	}

	public Vector2 getEnd() {
		return end;
	}
	
	@Override
	protected void renderFixture(Graphics2D g, double scale, BodyFixture fixture, Color color) {
		Stroke stroke = g.getStroke();
		g.setStroke(new BasicStroke(1));
		super.renderFixture(g, scale, fixture, color);
		g.setStroke(stroke);
	}
	
}
```

**Comment by wnbittle** [comment]
Thank you for the additional information.  The problem is a bug in the Segment/Link raycast detector specifically when using perfectly vertical segments.  I've applied a fix to the source and will include in the next release.

**Comment by prat-man** [comment]
Thank you for looking into the issue and releasing a fix. Can you please tell me when to expect the next release? Also, is it possible to directly use the latest source code before the next release is out since I am stuck without the fix.

**Comment by prat-man** [comment]
Thank you. I shall try to use the latest source. That way I can test the fix as well and will let you know if it is working fine. Also, I would like to thank you for the brilliant work that you are doing.
