### ISSUE TITLE
WoundIterator skips first element of the array

### ISSUE THREAD

**Issue by Sleafar** [dyn4j/dyn4j#69]
The index in WoundIterator is not initialized explicitly, which means it's automatically initialized as 0. The consequence of this is that the first element retrieved by the iterator is the element at index 1, because the index is incremented before the element is retrieved. The index should be initialized as -1.

**Comment by wnbittle** [comment]
Thank you for reporting.  I've verified, added a unit test, and fixed the issue.  The fix will be included in the next release.

**Comment by Sleafar** [comment]
I haven't tested it, but doesn't it now skip the last element? I think "hasNext()" is now returning "false" too early.

**Comment by wnbittle** [comment]
You are correct.  I've made the fix and added another test to ensure it iterates all the items.
