### ISSUE TITLE
Java Default UUID in AbstractShape is bad for concurrency

### ISSUE THREAD

**Issue by nsoft** [dyn4j/dyn4j#71]
I've got some code where I'm triangulating a set of polygons. They can be triangulated independently and so parallelized the process to leverage my 32 thread cpu. I saw almost no speed up. (less than a factor of 2). When I fired up YourKit and profiled all my threads were full of red blocking on sun.security.provider.SecureRandom.EngineNextBytes() which is a synchronized method on the single instance of NativePRNG (which implements SecureRandomSPI) that the JDK uses to generate UUID's 

This is the basic form of the code:
````
      List<HullPrinter> printers = new ArrayList<>();
      for (List<Hull> datum : data) {
        for (Hull hull : datum) {
          printers.add(new HullPrinter(new StringWriter(), hull));
        }
      }
      printers.parallelStream().forEach(printer -> {
        try (PrintWriter pw = new PrintWriter(printer.sw)) {
          Converter.writeTriangles(printer.hull, pw);
        }
      });
      for (HullPrinter printer : printers) {
        printWriter.print(printer.sw.toString());
      }
````
Where `writeTriangles()` eventually calls `SweepLine.triangulate()` which in turn causes a very large number of calls to create instances inheriting from `AbstractShape` and that's where the UUID is created. I saw Issue #47 and read a good chunk of it but I don't actually care if you use numbers or UUID's what I'd like to propose is that one way or another a more threading friendly solution be employed. (I may suggest something specific soon if I find an improved solution, for which I will first look for faster UUID generators because that's a smaller change)

**Comment by nsoft** [comment]
It looks like the following package can provide UUID's based on whatever implementation of Random you prefer:
````
    compile 'com.fasterxml.uuid:java-uuid-generator:3.1.4'
````
The code change looks like:
````
public abstract class AbstractShape implements Shape, Transformable, DataContainer {
	// not cryptographically secure, but since this isn't actually cryptography we should be fine
	// so long as shapes are not used as passwords somewhere ;). This allows parallel
	// threads to operate about 8 times faster on a 32 thread CPU vs the default UUID.
	/** The shape's unique identifier */
	protected final UUID id = Generators.randomBasedGenerator(new Random()).generate();
````
The processors on my machine are now fully utilized, and the 8 minute operation is now down to 1 minute.

If the java.util.Random() makes you nervous or you feel that collisions are too likely you can just implement your own (or find another impl, just not the impls for SecureRandom that the JDK brings in because even the "non blocking" one is synchronized badly.) Pull request shortly...

**Comment by nsoft** [comment]
Well, the particular library I chose above seems to cause difficulties in the build... it requires a module called "log4j" but that module name doesn't appear to be exported from anything, this causes a sysout, which then breaks surefire...

**Comment by wnbittle** [comment]
I think the solution I proposed in #47 is the correct approach.  The solution was to modify the library to allow the user to specify how to generate ids.  This would allow you to avoid UUIDs completely and keep dyn4j free of dependencies.

**Comment by wnbittle** [comment]
Based on the discussion in #47 this will not be a problem in versions > 3.3.1.  There will be a 3.3.1 release that will mark the ids as deprecated for removal.  Then the following release will remove them.

**Comment by wnbittle** [comment]
The next step with this issue is to remove the getId methods from the library.

**Comment by wnbittle** [comment]
This is complete and checked into master.  If/When you get a chance, @mtsamis, please review to make sure I didn't miss anything and for additional testing.

**Comment by mtsamis** [comment]
Hey @wnbittle I looked at the commit; everything looks good but I have a suggestion to improve toString implementations. You removed id from toString methods and while this is not technically a problem it makes it possibly harder to read console output. For example printing a body will output very much stuff so you could see the id and distinguish different bodies easily without having to look at other data. Maybe we should use again System.identityHashCode(x) to replace printing of ids? Although there can be collisions it would be a helpful ‘tag’ to recognize objects in the output.

Also will this break some of the sandbox code? I recall it used IDs to deserialize joints and such. Maybe we should look at this too.
