### ISSUE TITLE
Null Pointer Exception during Triangulation

### ISSUE THREAD

**Issue by nsoft** [dyn4j/dyn4j#72]
```
Caused by: java.lang.NullPointerException
	at org.dyn4j.geometry.decompose.SweepLine.regular(SweepLine.java:258)
	at org.dyn4j.geometry.decompose.SweepLine.createTriangulation(SweepLine.java:128)
	at org.dyn4j.geometry.decompose.SweepLine.triangulate(SweepLine.java:79)
```
This seems to occur at random points during triangulation. I'm triangulating polygons sliced from an STL that had ~25000 triangles to create an STL surface, so there's a lot of opportunity to hit edge cases I suspect. Unfortunately it also means that there's a ton of prior calculations and tracking down why it happens is a minor nightmare...

For reference this happens via this code:
```
  public List<Triangle> toTrianglesInPlane(List<Point3D> points) {
    SweepLine sl = new SweepLine();
    List<Vector2> vector2s = projectToPlane(points);
    return sl.triangulate(vector2s.toArray(new Vector2[]{}));
  }
```
Since at this point I'm only dealing with planes orthogonal to the Z axis the project to plane code is trivial... There are multiple threads running this in parallel but the Point3D objects are immutable and as you can see the code creates a new Sweepline within each thread so unless you reference mutable statics it should be safe.

(Dyn4j 3.3.0)

**Comment by wnbittle** [comment]
Would you be able to try the latest source code? I found and fixed some issues with SweepLine specifically, but haven’t made a new release yet.

**Comment by gus-asf** [comment]
I'll give it a shot, but it's pulled in via gradle dependency so a release would be appreciated... here's what I see in the debugger:
![image](https://user-images.githubusercontent.com/46900717/68062934-cc7c8880-fce3-11e9-9a11-3733670a38f1.png)

**Comment by gus-asf** [comment]
Same problem shows up in ce0acd76b39e6068fc97284215ae171c59ab4dab (master)

**Comment by wnbittle** [comment]
Can you supply a reproduction case?  A file or list with the vertices of the simple polygon is really all I would need.  Do the other decomposition methods have the same problem?

**Comment by gus-asf** [comment]
Unfortunately, there's a lot of proprietary code that goes into creating those points so a code example broader than the above will be very difficult. Presently the data that this comes from is also restricted, but something less restricted will be used against the code soon. If I can, I'll try to capture something but it's likely to be a pretty large file.

**Comment by mtsamis** [comment]
@wnbittle @gus-asf I have reproduction polygons for this bug + some more cases for triangulation, I will upload them shortly.

@gus-asf I think your polygons are ill-shaped (self intersections probably?). But then SweepLine should have checks for those cases and throw an appropriate error.

**Comment by gus-asf** [comment]
I've finally managed to find coordinates that fail, they appear to be more or less all in a straight line (zero area) I'd be happy to just ignore these (prior code tries to weed them out but apparently it occasionally fails), so if you can throw a ZeroAreaPolygonException or something like that it would be fine.

**Comment by wnbittle** [comment]
I'm going to close this and track this issue from #75 .  I've moved the sample you provided over there as well.
