### ISSUE TITLE
Issues in triangulate and hull packages

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#73]
After #72 I did some randomized testing for the hull and triangulation algorithms and found some (possible) issues in various of the algorithms. I have not yet examined the results but those are a good starting point to reproduce some behaviors that need examination.

I have included some with extreme floating point values. Maybe some with very extreme values can be dismissed.

**`SweepLine`**: First of all there are issues in the `SweepLine` class, that include those in #72. I think all of those come from non-simple polygons. If so there needs to be added a test for non simple polygons to throw a proper exception.

- `new Vector2[] {new Vector2(0.1595990921676319, 0.20158036631684495),new Vector2(0.3627243978540108, -0.2125801642934565),new Vector2(0.4972213824759445, -0.2197501458724339),new Vector2(-0.17530050402164232, -0.10202036313267437)}` 
Exception in thread "main" java.lang.NullPointerException
	at org.dyn4j.geometry.decompose.SweepLine.regular(SweepLine.java:258)

- `new Vector2[] {new Vector2(0.187521000630546, -0.2171227524343904),new Vector2(-0.05418163781638374, -0.4552384293706746),new Vector2(-0.12615265827683775, 0.08842525905551823),new Vector2(-0.4197343412893181, -0.45293439849558936)}`
Exception in thread "main" java.lang.NullPointerException
	at org.dyn4j.geometry.decompose.SweepLine.merge(SweepLine.java:223)

- `new Vector2[] {new Vector2(-0.22574647794211955, 0.3562272754868271),new Vector2(-0.24724056392833493, -0.06552204150010887),new Vector2(0.2551995234048088, -0.4678431592201415),new Vector2(-0.11272047497863902, -0.40936273068655504)}`
Exception in thread "main" java.lang.NullPointerException
	at org.dyn4j.geometry.decompose.SweepLine.split(SweepLine.java:190)

- `new Vector2[] {new Vector2(-0.07792188619765694, 0.10364292899125216),new Vector2(0.2412466770151972, -0.3145214553981004),new Vector2(0.21037640391727175, 0.06289919008100842),new Vector2(0.3079072605141815, -0.20863138522549773)}`
Causes infinite loop

**`GiftWrap`**: GiftWrap and DivideAndConquer seem to have issues when there are a lot of colinear points (mine happened to be at 1.0)

- `new Vector2[] {new Vector2(23.854242711277, 1.0),new Vector2(57.707453390935676, 1.0), new Vector2(13.0, 1.0), new Vector2(27.918475169266998, 1.0)}`

- `new Vector2[] {new Vector2(10.168247682384637, 1.0),new Vector2(578.481435182016, 1.0),new Vector2(1.0, 1.0), new Vector2(56794.911916994446, 0.03868539926533467)}`

- `new Vector2[] {new Vector2(1.0, 1.0),new Vector2(1.0, 1.0),new Vector2(9135172.538699752, 1594.2921033236523), 
new Vector2(1.0, 3436.444789677664),new Vector2(53371.47726301303, 63.201463180191396), new Vector2(1.0, 1.0),new Vector2(0.09713620217398017, 286668.0866273699), new Vector2(104.83526669412421, 579.583503857007)}`

- `new Vector2[] {new Vector2(69464.96179292782, 0.05006981639456297), new Vector2(0.03735960666625501, 0.3783853688716485), new Vector2(334.68865889609134, 3.955720227287777E-23), new Vector2(5.758935896542613E22, 8.12199057379559E21)}`

All cause infinite loop and/or OutOfMemoryError.

**`DivideAndConquer`**: Similar with GiftWrap

- `new Vector2[] {
new Vector2(9.67305424383519, 114.09907896473986),new Vector2(1.0, 1161.9752606517477), new Vector2(1.0, 1.0),new Vector2(1.0, 10.546088997659012), new Vector2(22.088494561091807, 230.94365885699824), new Vector2(2.8366426821689994, 1.0),new Vector2(8.944224404040732, 6.315177488492587), new Vector2(1.0, 59.98064323348245), new Vector2(9.24861145190379, 8404.268678968832),new Vector2(1.0, 0.03504029713737921),new Vector2(1.0, 82.55330004652801)}`

- `new Vector2[] {new Vector2(1.0, 1.5767304065549268E12), new Vector2(1.870841152451107, 6.534140012505794E23), new Vector2(1.9603053816739006E12, 9.074076290143341E10), 
new Vector2(3260266.640396411, 7.796498271329308E7), new Vector2(28.709287118505284, 82447.5698720256), new Vector2(1.8463774403168068E15, 0.013098511687408589), 
new Vector2(3740193.601814064, 4682.6340006396895), new Vector2(3170758.3618271016, 2.131083797649407E7), new Vector2(143.83527343008367, 3.2294659543003845E15), 
new Vector2(1.0, 5.956908518731977E17), new Vector2(2.0531014115467064E-7, 2306510.1010659263), new Vector2(1.2474786776966758E20, 1.4802417824918536E11), 
new Vector2(1.0, 15.084034859698757)}`

All cause infinite loop and/or OutOfMemoryError.

The rest hull algorithms seem to be tolerant to both extreme fp values as well as colinear points.
I'll perform some further testing later.

**Comment by wnbittle** [comment]
Split into #76 and #75 to manage the type of issue better.
