### ISSUE TITLE
Are Forces and Velocity local or global?

### ISSUE THREAD

**Issue by HelloMaybeIDontKnow** [dyn4j/dyn4j#74]
Might be a stupid question but I can't find a hint on that matter, neither in source nor on the website nor on the documentation.
Are get/set force/velocity on bodies relative to the bodies roation or relative to global coordinates?

**Comment by wnbittle** [comment]
Force and velocity are comprised of two components: magnitude and direction.  The direction should be in world space coordinates.  The magnitude is neither local nor world space.  If you are applying a Force at a location via `applyForce(Vector2,Vector2)`, then the location should also be in world space coordinates.

I've added some javadoc comments to the methods for others.

**Comment by HelloMaybeIDontKnow** [comment]
Thank you :)
