### ISSUE TITLE
Bump version to 3.4.0

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#78]
I think at this point we should bump the next release to 3.4.0 instead of 3.3.1. As per what the Version class indicates:
`/** The minor version number; medium impact changes; minor API changes, minor enhancements, 
major bug fixes, etc. */`
vs
`/** The revision number; low impact changes; deprecating API changes, minor bug fixes, etc. */`

Up from 3.3.0 (https://github.com/dyn4j/dyn4j/compare/3.3.0...master) we have lots of
> medium impact changes; minor API changes, minor enhancements, 
major bug fixes

so I propose to mark the next release as 3.4.0.
If this change is ok I can take care of making a PR with the necessary changes.

**Comment by wnbittle** [comment]
I think this is fine.  Should be a easy find/replace.

**Comment by mtsamis** [comment]
Yes, done in #86
