### ISSUE TITLE
Discussion for Transform.IDENTITY

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#79]
This is not a major issue, but I find the static IDENTITY field of the Transform class somewhat 'ugly'. I know Java does not have a good mechanism to make immutable objects of mutable classes, but there are probably more ways to approach this. This also (in theory) has some performance implications because when this overridden Transform field is used the call sites with Transform arguments will see a 'new type of transform object' (i.e. JVM is quite good to optimize monomorphic  method calls). So I want to discuss the possibilities:

1. Remove the Transform.IDENTITY field and add private IDENTITY constants to the (2-3) classes that use this internally. Users can have their own version of this constant since it's construction is trivial (`new Transform()`). This was my initial test and I actually have a old-ish spare implementation of it [minor_tranform branch](https://github.com/mtsamis/dyn4j/tree/minor_transform) as a sample implementation
2. Keep the Transform.IDENTITY field but do not override any methods (i.e. `public static final Transform IDENTITY = new Transform();`) alongside with a note to the user, as in the Vector2 class `...this vector should not be changed at runtime; used internally...`
3. Do nothing and keep current implementation

In my opinion:
- 1 is quite feasible; On the user side it should be very easy to refactor the code to use a personal Transform constant (or at least certainly easier that what required by the future of #47)
- 2 is easy to implement but can lead to some nasty bugs in rare scenarios. I would personally avoid such implementation
- 3 is totally feasible but bad for my aesthetics :grin:

**Comment by wnbittle** [comment]
Agreed, it's ugly.  I'd prefer the 1st option.

**Comment by wnbittle** [comment]
Was thinking about something - how do you feel about leaving a `public static final Transform IDENTITY = new Transform();` in the Transform class with a `@Deprecated` attribute on it for compatibility?

**Comment by mtsamis** [comment]
Yeah, this sounds even better. I don't even know if it should be marked as deprecated actually.
Since now internally dyn4j uses it's own private instances that cannot be mutated by the user, maybe we can have this `public static final Transform IDENTITY = new Transform();` field in the Transform class for uses in user code.
Do you think it should be deprecated, or not?

**Comment by wnbittle** [comment]
Ok, how about this - we don't deprecate it but we reiterate the fact that all `Transform` instances are mutable?  I think if I had my choice I would just deprecate it.

**Comment by mtsamis** [comment]
Well, my initial problem was to let it be mutable because it was used internally in dyn4j. So something bad could happen to it and then simple methods that e.g. take no arguments could result to something wrong; this is a hard bug to find.

But since now the field isn't used internally (all classes have a private constant), the worse thing that can happen is only in the user side. My point is: *In this case it wouldn't make any difference if the field was declared in user code or in the Transform class* (So why not have it there for convinience?).

Just so I can understand the reason better: Do you want to deprecate the field and remove it in the future, or deprecate it and just leave it like that?

**Comment by wnbittle** [comment]
I’m not sure.  My original thought was that keeping the public static field would imply immutability and a slightly selfish desire to not have bug reports from users that are hard to troubleshoot.  So I was thinking leave it in, mark it deprecated with a message that explains why, then remove later down the road.

So my thought was more around perception, which we could probably solve with comments too.

**Comment by mtsamis** [comment]
Alright, fine with me. Then let's have it like that.
Add the field back as a simple transform instance, deprecate it for removal with corresponding javadoc explanation then remove in future release.

**Comment by wnbittle** [comment]
I've added it back with deprecated markers.
