### ISSUE TITLE
Discussion for hull algorithms

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#81]
While studying and examining the relevant hull algorithms, apart from the bugs, it seems that the results of the different algorithms greatly vary, especially given some 'edge cases': co-linear points, duplicate points, zero area 'polygons' etc.

I was thinking that it would be nice to have some defined consistent description of what should happen in all those cases and then (try to) re-implement the algorithms to adhere to those rules.
Then 1) the user can easily change algorithms (e.g. for performance) without sudden strange results and also 2) we can have more meaningful and complete unit tests + use each algorithm to validate the others.

From my current tests it seems that the MonotoneChain algorithm is a good quality benchmark: de-duplicates points, graciously removes co-linear points, handles zero area polygons in a meaningful way. Maybe it's behavior could be the basis of the expected result? (correct me if I'm wrong - if there are cases where the above do not hold for this algorithm).

I have not examined how feasible it is to make all algorithms have the same properties.
I was working on some fix for the hull bugs but because most of them have to do with those edge cases it felt like there should be some expected behavior to follow before making another implementation.

**Comment by wnbittle** [comment]
With the work on `GiftWrap` and `DivideAndConquer` I'm making progress towards that, but also finding that each of these has their own drawbacks wrt. robustness.  As I fix the issues I'm seeing them get closer to a unified operation.  There still might be differences though.  One example in my mind is the order of the vertices of the hull.  For example, for a hull with 20 points, `GiftWrap` may choose point 4 to be index 0 in the resulting hull and `DivideAndConquer` might choose point 10.

Let's revisit once the bugs are cleaned up.

**Comment by mtsamis** [comment]
Alright, fair enough. I'm leaving the bugs to you then since you made good progress.
Point order should not be standard, yeah, since this will probably impose a non-trivial performance penalty from some algorithms. At the end we could just document the expected behavior on a per-algorithm basis.
