### ISSUE TITLE
Avoid non-deterministic unit tests

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#84]
One small note:
The new ConvexHull test classes in 1134b731412055bfa1f6e7e7e49d4f6d6874baf4 use `Math.random()` to generate a random point cloud, making the test to be non-deterministic. This is somewhat troublesome and the test can randomly fail/pass. You can change it to be deterministic, as in `BroadphaseTest`

That is, instead of
```java
int size = (int) Math.floor(Math.random() * 96.0 + 4.0);
```

Something like
```java
private static final int SEED = 0;
...
Random r = new Random(SEED);
int size = (int) Math.floor(r.nextDouble() * 96.0 + 4.0);
```

This applies to `MonotoneChainTest`, `GrahamScanTest`, `GiftWrapTest` etc

**Comment by wnbittle** [comment]
Agreed.  This was done in 2bffbcb46ed71ee39ebba7c1c1d101ac244a8388
