### ISSUE TITLE
[Minor] Wrong exception message

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#90]
https://github.com/dyn4j/dyn4j/blob/2bffbcb46ed71ee39ebba7c1c1d101ac244a8388/src/main/java/org/dyn4j/geometry/Mass.java#L226-L230

The Exception message here should probably be `"geometry.mass.nullMassListElement"` instead.

**Comment by wnbittle** [comment]
Yup.  I'll take care of it.
