### ISSUE TITLE
Memory allocations and stuff

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#92]
I have been making some measurements about memory usage/allocation rate with dyn4j. I know dyn4j does not go to great lengths in order to reduce allocations and such (and the resulting cleaner code is appreciated).

I found some small bits of code though where writing more memory allocation sensitive code can bring big ‘savings’. 
In my experiment (numbers are approximations from what I remember, but make the point):
2000 rectangle random-ish scene 
500 frame simulation 

Current version: ~120-130 million Vector2 allocations 
Version 1 (only rewrite of parts in Sequencial impulses algorithms): ~ 40-45 million allocations
Version 2 (version 1 + some more small scope changes in other places): ~20 million allocations 

This is from a draft experimental implementation, but the reasoning was to change only a few but critical parts. 
I think v1 could be a good candidate to actually implement. The changes are small and limited to one class yet the gains are quite good. v2 needs some discussion whether it is worth it for the extra bits.

On my desktop overall performance is unaffected by the changes, the GC is doing quite a good job. But on the other hand reducing the strain ‘for free’ should not be bad either. Also will probably help for lower end computers/mobiles. 

@wnbittle I would make a pull request, but didn’t knew how much memory sensitive code is ok (if at all)

**Comment by wnbittle** [comment]
Less object allocations are great.  What I try to do is weight the readability change vs. the improvement.  In my experience object allocation on modern VMs is ridiculously good, but on Android its lackluster at best.

I know that I don't want object pooling or array management.  Inlining is fine as long as the more readable code is available via comments.  Stuff like `v1.product(v2).sum(v3).difference(v4)` to `v5.x = (v1.x * v2.x) + v3.x - v4.x` would be fine.

Maybe if you gave a few examples of what you had in mind and I could speak to each?

**Comment by mtsamis** [comment]
Agreed, no object pooling (if you mean making x objects in some array and then reusing them) or strange array hacks in general, since those are ugly and error prone.
Most of what I did is
1) Inlining as you mentioned
2) Moving object allocations outside of 'hot' loops
3) Re-arrange code 

Here are some examples:
___
1) Inline to eliminate vector allocations:
```java
Vector2 p1 = c1.sum(r1);
Vector2 p2 = c2.sum(r2);
Vector2 dp = p1.subtract(p2);
double penetration = dp.dot(N) - contact.depth;
```
The above can become
```java
double dpx = (c1.x + r1.x) - (c2.x + r2.x);
double dpy = (c1.y + r1.y) - (c2.y + r2.y);
double dpDotN = dpx * N.x + dpy * N.y;
double penetration = dpDotN - contact.depth;
```
___
2) Use alternative method calls to move allocations outside (nested) loops:
```java
for (int i = 0; i < size; i++) {
    ...
    Vector2 c1 = t1.getTransformed(m1.getCenter());
    Vector2 c2 = t2.getTransformed(m2.getCenter());
```
The above can become
```java
Vector2 c1 = new Vector2();
Vector2 c2 = new Vector2();
for (int i = 0; i < size; i++) {
    ...
    t1.getTransformed(m1.getCenter(), c1);
    t2.getTransformed(m2.getCenter(), c2);
```
___
3) Reuse vectors that are declared outside (nested) loops
```java
for (int k = 0; k < cSize; k++) {
    ...
    Vector2 J = N.product(jp);
```
The above can become
```java
for (int k = 0; k < cSize; k++) {
    ...
    J.set(N).multiply(jp);
```
___
4) Perform multiple computations with one object where 'convinient':
```java
public Vector2 getFarthestPoint(Vector2 vector, Transform transform) {
    Vector2 localn = transform.getInverseTransformedR(vector);
    int index = getFarthestVertexIndex(localn);
    return transform.getTransformed(this.vertices[index]);
}
```
The above can become
```java
public Vector2 getFarthestPoint(Vector2 vector, Transform transform) {
    Vector2 localn = transform.getInverseTransformedR(vector);
    int index = getFarthestVertexIndex(localn);
    transform.getTransformed(this.vertices[index], localn);
    return localn;
}
```
___
5) Use local variable as internal allocated memory:
```java
private double getRelativeVelocityAlongNormal(ContactConstraint contactConstraint, Contact contact) {
    Vector2 rv = this.getRelativeVelocity(contactConstraint, contact);
    return contactConstraint.normal.dot(rv);
}
```
The above can become
```java
private final Vector2 buffer = new Vector2();
private double getRelativeVelocityAlongNormal(ContactConstraint contactConstraint, Contact contact) {
    this.getRelativeVelocity(contactConstraint, contact, buffer);
    return contactConstraint.normal.dot(buffer);
}
```
___

Those are probably all the 'patterns' I applied and got to reduce the total Vector2 allocations as the issue says. In my opinion:
1 is ok to use almost anywhere with the appropriate comments
2-3 are ok to use but only on limited places where *a lot* of allocations are eliminated and it's worth it
4 is not really great to do
5 is not really great to do but in specific circumstances can be profitable

So with those I experimented to make
Version 1 = use 1, 2, 3 & 5 without contraints but only within a single class (SequencialImpulses)
Version 2 = v1 + limited use of all in other 'hot' classes/methods

**Comment by wnbittle** [comment]
I would consider 1-3 acceptable with original code commented out (or sufficient English comments) but only where there's a significant benefit.  4-5 I wouldn't want at all - too risky.  Speaking for myself here, I would most certainly introduce a bug this way.

I feel like we're nearly in alignment.  I would suggest we start at SequentialImpulses for example and see what 1-3 does for us.

**Comment by mtsamis** [comment]
Ok I'll follow up here with some sample implementations using patterns 1-3.

**Comment by TMIndust** [comment]
In the old forum (a long time ago) these exact changes were discussed but it was hard to keep track and it died.

To share some insights from way back:
On Desktop Java these "allocation saving improvements" have nearly no measurable effect on performance. The JVM is amazingly fast in that regard.

Android (Lollipop and onwards) behaves similar, performance impact of object creation are minor. The main problem is the Garbage Collector. If the GC can't keep up with the temporary objects created, memory will steadily rise until the JVM has to allocate more system memory. Which Android tries to prevent first, by an in-depth garbage collection, causing the application to pause for a noticable amount of time every few seconds.

What I am trying to say: One can gain performance by reducing object allocations below the memory churn rate of the device. After that, the impacts are minor. Newer Android versions improve steadily towards Desktop Java performance, just a matter of time.
It would be best to concentrate on easy hotspots first, test them against a specific target device and see if this solves the problem, already.

**Comment by mtsamis** [comment]
Yeah this is pretty much it. I think I actually remember seeing the discussion in the forum back in the day as well :)

I can confirm that on desktop allocations are close to free. What is good is that the majority of all allocations happen in the SequencialImpulses class so we can optimize a bit there and the total number of allocations becomes much smaller 'for free' (this is the definite hotspot for allocations).
I have no devices to test on unfortunately, but as long as the changes do not decrease code quality and are contained in a small set of classes I don't see much potential issues with it.

**Comment by TMIndust** [comment]
I can test the code changes against different devices. I just need to know for which device and Android version.

However, I don't have a dyn4j benchmark or anything like that. If someone accidentially happens to have one...

**Comment by wnbittle** [comment]
@mtsamis No pressure at all, just wondering if you had more changes coming with this one and if so, did you want to target 3.4.0 or 3.4.1 (so i can mark it appropriately).  With the holidays coming I'll have a little more time and would like to release 3.4.0 sometime in the next week or two.

**Comment by mtsamis** [comment]
Sounds good to make the 3.4.0 release in the holidays!

Let's leave this one for 3.4.1; I have most of those already implemented somewhere but I'll have to clean up, document, organize it etc. It's not that important change anyway.

**Comment by wnbittle** [comment]
@mtsamis  With 4.x out now are there additional changes that you are planning to implement?  Either way it would probably make sense to close this issue.
