### ISSUE TITLE
Suggestion for change in Ray constructor

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#94]
In the raycast implementation used in the broadphases there is
```java
Vector2 d = ray.getDirectionVector();
```
which later is also used as
```java
double w = d.x * length;
double h = d.y * length;
```
But the returned vector from `Ray#getDirectionVector` is *not* a unit vector hence the length of the ray ends up *not* being what a user could expect. I believe this should be changed; Must be as easy as normalizing the vector in the `Ray` constructor.

**Comment by TMIndust** [comment]
The constructor asks for a "direction" vector. The method returns a "direction" vector. I don't think the argumentation is valid to expect something different to be returned.
On top of that, the documentation of the constructor explicitly states:

> 	 * @param direction the direction; must be normalized

I did fall into the same pit as you did, causing interesting raycasting results. Still, I am not sure if I am supporting your request.

**Comment by mtsamis** [comment]
Oops thanks for the doc reference, I definitely missed it :)

But still it seems this point can cause some subtle/confusing bugs so why not do something about it?
I think this is not in alignment with the rest of the library i.e. validate/ensure conditions even if there's a small theoretical performance penalty.

So why not normalize the `Vector2` argument here? I can't imagine `.normalize` in the `Ray` constructor being a bottleneck; the raycast operation will take multiple orders of magnitude that time.

If there's a problem I'm missing with this approach we should at least validate the input (as for the other cases) with a simple `Math.abs(direction.getMagnitudeSquared() - 1) < Epsilon.E`.

Thoughts?

**Comment by wnbittle** [comment]
I'm open to changing the Ray constructors to normalize the given direction vector, but the thought was that performance would be better if the user was responsible for normalization.  That said, it is concerning that the javadoc comment was missed and both of you encountered strange behavior because of it.

I like the idea of verifying that the given direction is normalized, but we're only a sqrt away from normalizing it ourselves that way.

**Comment by mtsamis** [comment]
Yeah, I personally suggest to just normalize anyway; as I mentioned above the cost of the normalization is trivial in regard to the actual raycast operations. I see no scenario where this normalization can be an issue/bottleneck.

**Comment by wnbittle** [comment]
I updated the Ray constructor to normalize the incoming direction vector.
