### ISSUE TITLE
Preparing for the 3.4.0 release

### ISSUE THREAD

**Issue by mtsamis** [dyn4j/dyn4j#96]
We can use this issue to discuss anything needed for the upcoming 3.4.0 release.

Here are some things I would like to discuss:
- **Default Broadphase detector** - I think I had mentioned this sometime but I really think we should make `LazyAABBTree` the dafault broadphase detector used in the World class. The performance difference is really big and I have found no cases where it performs worse than the existing `DynamicAABBTree`. Because not many people will go as far as to modify the default broadphase detector the benefits won't reach the "casual user" otherwise.
If more evidence for it's performance is needed or an in-depth comparison with `DynamicAABBTree` in order to be evaluated I can work on those.
- **Release notes** - We should update the release notes to reflect latest changes. Here are some ideas for things that could/should be mentioned:
    - important to note: getUUID is deprecated and will be removed in the next version
    - new Rotation class that can be used to efficiently handle rotations
    - copy() methods introduced
    - new methods for Vector2: divide/quotient & inverseRotate
    - Transform.IDENTITY deprecated
    - (soon) RobustGeometry class that will host numerically robust versions of geometric algorithms
    - (possible) the change about the Ray constructor; depending on what will be done about it
    - more tests added

    Those can be sorted by significance of course but I believe it is nice to let users know enough details of possible new things they can take advantage of.

**Comment by wnbittle** [comment]
@mtsamis Can you clarify where the copy() methods were added?

**Comment by wnbittle** [comment]
I've updated the release notes with the information above (apart from my question about the `copy` methods).  Let me do some more testing with the new broadphase.

**Comment by wnbittle** [comment]
I've decided to wait to replace the default broadphase detector.  No official release has included it yet, so I'd like to make this release include it as an option, then in a subsequent release we can update the default BP.

**Comment by mtsamis** [comment]
Ok, sounds like a good idea to give some time before any possible changes. Thanks
